// import 'package:marikina_market_mobile/features/tickets/domain/entities/inspection_ticket_summary.dart';
// import 'package:marikina_market_mobile/features/tickets/domain/enums/sync_status.dart';
// import 'package:marikina_market_mobile/features/tickets/domain/enums/ticket_severity.dart';
// import 'package:marikina_market_mobile/features/tickets/domain/enums/ticket_type.dart';

// final List<InspectionTicketSummary> mockInspectionTicketSummaries = [
//   InspectionTicketSummary(
//     ticketId: 11861,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.high,
//     businessName: 'Patatas ni Kian Stall',
//     marketSection: 'Market Section A',
//     stallNumber: 'B-12',
//     vendorFirstName: 'Kian',
//     vendorLastName: 'Stall',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-07-03T14:27:00Z'),
//     overDueDate: DateTime.parse('2026-07-17T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11862,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.medium,
//     businessName: 'Fresh Tuna at Ukayan ni Mhar',
//     marketSection: 'Market Section B',
//     stallNumber: 'D-2',
//     vendorFirstName: 'Mhar',
//     vendorLastName: 'Ukayan',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code', 'Ord. #150 Series Of 2001 Sanitation Code'],
//     createdAt: DateTime.parse('2026-07-03T14:27:00Z'),
//     overDueDate: DateTime.parse('2026-07-20T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11863,
//     ticketType: TicketType.warning,
//     severity: TicketSeverity.low,
//     businessName: 'Jerick Gulayan at Gulaman',
//     marketSection: 'Market Section A',
//     stallNumber: 'B-12',
//     vendorFirstName: 'Jerick',
//     vendorLastName: 'Gulayan',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-07-02T13:00:00Z'),
//     overDueDate: DateTime.parse('2026-07-16T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11864,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.high,
//     businessName: 'Barbershop ni Nuno',
//     marketSection: 'Market Section C',
//     stallNumber: 'A-5',
//     vendorFirstName: 'Nuno',
//     vendorLastName: 'Barbero',
//     ordinance: ['Ord. #150 Series Of 2001 Sanitation Code'],
//     createdAt: DateTime.parse('2026-07-01T09:15:00Z'),
//     overDueDate: DateTime.parse('2026-07-08T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11865,
//     ticketType: TicketType.warning,
//     severity: TicketSeverity.medium,
//     businessName: 'Manang Fish Vendor',
//     marketSection: 'Market Section B',
//     stallNumber: 'D-9',
//     vendorFirstName: 'Rosa',
//     vendorLastName: 'Manalo',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-06-30T11:42:00Z'),
//     overDueDate: DateTime.parse('2026-07-14T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11866,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.low,
//     businessName: 'Fruit Stand ni Aling Nena',
//     marketSection: 'Market Section A',
//     stallNumber: 'B-7',
//     vendorFirstName: 'Nena',
//     vendorLastName: 'Reyes',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-07-04T08:20:00Z'),
//     overDueDate: DateTime.parse('2026-07-25T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11867,
//     ticketType: TicketType.warning,
//     severity: TicketSeverity.high,
//     businessName: 'Karinderya ni Tessie',
//     marketSection: 'Market Section C',
//     stallNumber: 'A-1',
//     vendorFirstName: 'Tessie',
//     vendorLastName: 'Cruz',
//     ordinance: ['Ord. #150 Series Of 2001 Sanitation Code'],
//     createdAt: DateTime.parse('2026-07-05T15:50:00Z'),
//     overDueDate: DateTime.parse('2026-07-12T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11868,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.medium,
//     businessName: 'Sari-Sari Store ni Mang Tomas',
//     marketSection: 'Market Section D',
//     stallNumber: 'E-3',
//     vendorFirstName: 'Tomas',
//     vendorLastName: 'Villanueva',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code', 'Ord. #151 Series Of 2015 Fire Safety Code'],
//     createdAt: DateTime.parse('2026-07-06T10:05:00Z'),
//     overDueDate: DateTime.parse('2026-07-22T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11869,
//     ticketType: TicketType.warning,
//     severity: TicketSeverity.low,
//     businessName: 'Meat Shop ni Kuya Ben',
//     marketSection: 'Market Section B',
//     stallNumber: 'D-4',
//     vendorFirstName: 'Ben',
//     vendorLastName: 'Santos',
//     ordinance: ['Ord. #150 Series Of 2001 Sanitation Code'],
//     createdAt: DateTime.parse('2026-07-06T16:30:00Z'),
//     overDueDate: DateTime.parse('2026-07-21T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11870,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.high,
//     businessName: 'Palengke Snacks ni Aling Baby',
//     marketSection: 'Market Section A',
//     stallNumber: 'B-15',
//     vendorFirstName: 'Baby',
//     vendorLastName: 'Fernandez',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-07-07T13:10:00Z'),
//     overDueDate: DateTime.parse('2026-07-10T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11871,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.medium,
//     businessName: 'Lechon Manok ni Aling Puring',
//     marketSection: 'Market Section D',
//     stallNumber: 'E-8',
//     vendorFirstName: 'Puring',
//     vendorLastName: 'Delacruz',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-07-07T09:40:00Z'),
//     overDueDate: DateTime.parse('2026-07-19T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11872,
//     ticketType: TicketType.warning,
//     severity: TicketSeverity.low,
//     businessName: 'Sapatos Repair ni Mang Ador',
//     marketSection: 'Market Section C',
//     stallNumber: 'A-9',
//     vendorFirstName: 'Ador',
//     vendorLastName: 'Ramos',
//     ordinance: ['Ord. #151 Series Of 2015 Fire Safety Code'],
//     createdAt: DateTime.parse('2026-07-08T11:20:00Z'),
//     overDueDate: DateTime.parse('2026-07-23T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11873,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.high,
//     businessName: 'Turo-Turo ni Aling Merly',
//     marketSection: 'Market Section A',
//     stallNumber: 'B-20',
//     vendorFirstName: 'Merly',
//     vendorLastName: 'Aquino',
//     ordinance: ['Ord. #150 Series Of 2001 Sanitation Code'],
//     createdAt: DateTime.parse('2026-07-08T14:55:00Z'),
//     overDueDate: DateTime.parse('2026-07-11T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11874,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.medium,
//     businessName: 'Gulay ni Mang Delfin',
//     marketSection: 'Market Section B',
//     stallNumber: 'D-11',
//     vendorFirstName: 'Delfin',
//     vendorLastName: 'Ocampo',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-07-09T07:30:00Z'),
//     overDueDate: DateTime.parse('2026-07-24T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11875,
//     ticketType: TicketType.warning,
//     severity: TicketSeverity.high,
//     businessName: 'Manicure at Pedicure ni Ate Joy',
//     marketSection: 'Market Section C',
//     stallNumber: 'A-13',
//     vendorFirstName: 'Joy',
//     vendorLastName: 'Salvador',
//     ordinance: ['Ord. #150 Series Of 2001 Sanitation Code'],
//     createdAt: DateTime.parse('2026-07-09T16:05:00Z'),
//     overDueDate: DateTime.parse('2026-07-13T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11876,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.low,
//     businessName: 'Palamig ni Kuya Jun',
//     marketSection: 'Market Section D',
//     stallNumber: 'E-6',
//     vendorFirstName: 'Jun',
//     vendorLastName: 'Mendoza',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-07-10T10:15:00Z'),
//     overDueDate: DateTime.parse('2026-07-26T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11877,
//     ticketType: TicketType.warning,
//     severity: TicketSeverity.medium,
//     businessName: 'Bulaklak ni Aling Remy',
//     marketSection: 'Market Section A',
//     stallNumber: 'B-3',
//     vendorFirstName: 'Remy',
//     vendorLastName: 'Torres',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code'],
//     createdAt: DateTime.parse('2026-07-10T12:40:00Z'),
//     overDueDate: DateTime.parse('2026-07-18T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11878,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.high,
//     businessName: 'Manghihilot ni Mang Boy',
//     marketSection: 'Market Section C',
//     stallNumber: 'A-17',
//     vendorFirstName: 'Boy',
//     vendorLastName: 'Garcia',
//     ordinance: ['Ord. #150 Series Of 2001 Sanitation Code'],
//     createdAt: DateTime.parse('2026-07-11T08:00:00Z'),
//     overDueDate: DateTime.parse('2026-07-09T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.pending,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11879,
//     ticketType: TicketType.ticket,
//     severity: TicketSeverity.low,
//     businessName: 'Tocino Factory ni Aling Editha',
//     marketSection: 'Market Section B',
//     stallNumber: 'D-14',
//     vendorFirstName: 'Editha',
//     vendorLastName: 'Bautista',
//     ordinance: ['Ord. #149 Series Of 1999 Market Code', 'Ord. #150 Series Of 2001 Sanitation Code'],
//     createdAt: DateTime.parse('2026-07-11T15:25:00Z'),
//     overDueDate: DateTime.parse('2026-07-27T00:00:00Z'),
//     isOverDue: false,
//     syncStatus: SyncStatus.synced,
//   ),
//   InspectionTicketSummary(
//     ticketId: 11880,
//     ticketType: TicketType.warning,
//     severity: TicketSeverity.medium,
//     businessName: 'Barbero ni Kuya Rey',
//     marketSection: 'Market Section D',
//     stallNumber: 'E-1',
//     vendorFirstName: 'Rey',
//     vendorLastName: 'Navarro',
//     ordinance: ['Ord. #151 Series Of 2015 Fire Safety Code'],
//     createdAt: DateTime.parse('2026-07-12T09:50:00Z'),
//     overDueDate: DateTime.parse('2026-07-15T00:00:00Z'),
//     isOverDue: true,
//     syncStatus: SyncStatus.pending,
//   ),
// ];