import 'package:marikina_market_mobile/features/tickets/domain/entities/ticket_summary.dart';
import 'package:marikina_market_mobile/features/tickets/domain/enums/ticket_status.dart';

final List<TicketSummary> mockTickets = [
  TicketSummary(
    controlNumber: "11861",
    ticketStatus: TicketStatus.active,
    businessName: "Patatas ni Kian Stall",
    stallNumber: "Stall No. B-12",
    marketSection: "Market Section A",
    createdAt: DateTime(2026, 7, 3, 22, 27),
    overDueDate: DateTime(2026, 7, 17, 22, 27),
    isOverDue: true, // As of July 15, 2026, it is past July 17... wait, actually July 17 is in the future. Correcting:
  ),
  TicketSummary(
    controlNumber: "11862",
    ticketStatus: TicketStatus.paid,
    businessName: "Fresh Tuna at Ukayan ni Mhar",
    stallNumber: "Stall No. B-12",
    marketSection: "Market Section A",
    createdAt: DateTime(2026, 7, 3, 10, 27),
    overDueDate: DateTime(2026, 7, 17, 10, 27),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11863",
    ticketStatus: TicketStatus.voidType, // Or 'void' depending on your enum naming
    businessName: "Jerick Gulayan at Gulaman",
    stallNumber: "Stall No. B-12",
    marketSection: "Market Section A",
    createdAt: DateTime(2026, 7, 3, 10, 27),
    overDueDate: DateTime(2026, 7, 17, 10, 27),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11864",
    ticketStatus: TicketStatus.disputed, // Or 'disputed' / 'appealed'
    businessName: "Barbershop ni Nuno",
    stallNumber: "Stall No. B-12",
    marketSection: "Market Section A",
    createdAt: DateTime(2026, 7, 3, 10, 27),
    overDueDate: DateTime(2026, 7, 17, 10, 27),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11865",
    ticketStatus: TicketStatus.active,
    businessName: "Gulayan Store",
    stallNumber: "Stall No. B-12",
    marketSection: "Market Section A",
    createdAt: DateTime(2026, 6, 25, 8, 15),
    overDueDate: DateTime(2026, 7, 9, 8, 15),
    isOverDue: true, // Overdue as of July 15, 2026
  ),
  TicketSummary(
    controlNumber: "11866",
    ticketStatus: TicketStatus.paid,
    businessName: "Aling Nena's Sari-Sari",
    stallNumber: "Stall No. C-04",
    marketSection: "Dry Goods Section",
    createdAt: DateTime(2026, 7, 1, 9, 30),
    overDueDate: DateTime(2026, 7, 15, 9, 30),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11867",
    ticketStatus: TicketStatus.active,
    businessName: "Kiko's Meat Shop",
    stallNumber: "Stall No. M-18",
    marketSection: "Wet Market Section",
    createdAt: DateTime(2026, 6, 28, 6, 45),
    overDueDate: DateTime(2026, 7, 12, 6, 45),
    isOverDue: true, // Overdue
  ),
  TicketSummary(
    controlNumber: "11868",
    ticketStatus: TicketStatus.paid,
    businessName: "Sizzling Plate Express",
    stallNumber: "Stall No. F-02",
    marketSection: "Food Court",
    createdAt: DateTime(2026, 7, 10, 12, 10),
    overDueDate: DateTime(2026, 7, 24, 12, 10),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11869",
    ticketStatus: TicketStatus.active,
    businessName: "Lito's Fruits & Veggies",
    stallNumber: "Stall No. V-09",
    marketSection: "Vegetables Section",
    createdAt: DateTime(2026, 7, 5, 15, 40),
    overDueDate: DateTime(2026, 7, 19, 15, 40),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11870",
    ticketStatus: TicketStatus.voidType,
    businessName: "Marikina Footwear & Leather",
    stallNumber: "Stall No. D-22",
    marketSection: "Dry Goods Section",
    createdAt: DateTime(2026, 7, 2, 11, 15),
    overDueDate: DateTime(2026, 7, 16, 11, 15),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11871",
    ticketStatus: TicketStatus.active,
    businessName: "Chona's Native Delicacies",
    stallNumber: "Stall No. F-15",
    marketSection: "Food Court",
    createdAt: DateTime(2026, 6, 30, 14, 20),
    overDueDate: DateTime(2026, 7, 14, 14, 20),
    isOverDue: true, // Overdue
  ),
  TicketSummary(
    controlNumber: "11872",
    ticketStatus: TicketStatus.disputed,
    businessName: "Bayan-Bayanan Fish Stall",
    stallNumber: "Stall No. W-05",
    marketSection: "Wet Market Section",
    createdAt: DateTime(2026, 7, 8, 5, 30),
    overDueDate: DateTime(2026, 7, 22, 5, 30),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11873",
    ticketStatus: TicketStatus.paid,
    businessName: "Golden Rice Dealer",
    stallNumber: "Stall No. G-11",
    marketSection: "Dry Goods Section",
    createdAt: DateTime(2026, 7, 6, 10, 00),
    overDueDate: DateTime(2026, 7, 20, 10, 00),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11874",
    ticketStatus: TicketStatus.active,
    businessName: "Mang Pepe's Native Lechon",
    stallNumber: "Stall No. M-03",
    marketSection: "Wet Market Section",
    createdAt: DateTime(2026, 6, 29, 7, 15),
    overDueDate: DateTime(2026, 7, 13, 7, 15),
    isOverDue: true, // Overdue
  ),
  TicketSummary(
    controlNumber: "11875",
    ticketStatus: TicketStatus.paid,
    businessName: "Elena's Plastic & Packaging",
    stallNumber: "Stall No. D-08",
    marketSection: "Dry Goods Section",
    createdAt: DateTime(2026, 7, 4, 16, 45),
    overDueDate: DateTime(2026, 7, 18, 16, 45),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11876",
    ticketStatus: TicketStatus.active,
    businessName: "Marikina Bakery Cafe",
    stallNumber: "Stall No. F-07",
    marketSection: "Food Court",
    createdAt: DateTime(2026, 7, 12, 8, 00),
    overDueDate: DateTime(2026, 7, 26, 8, 00),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11877",
    ticketStatus: TicketStatus.active,
    businessName: "Rene's Poultry Supply",
    stallNumber: "Stall No. W-14",
    marketSection: "Wet Market Section",
    createdAt: DateTime(2026, 6, 24, 6, 00),
    overDueDate: DateTime(2026, 7, 8, 6, 00),
    isOverDue: true, // Overdue
  ),
  TicketSummary(
    controlNumber: "11878",
    ticketStatus: TicketStatus.paid,
    businessName: "Tindahan ni Totoy",
    stallNumber: "Stall No. B-01",
    marketSection: "Market Section A",
    createdAt: DateTime(2026, 7, 7, 11, 30),
    overDueDate: DateTime(2026, 7, 21, 11, 30),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11879",
    ticketStatus: TicketStatus.voidType,
    businessName: "Freddie's Electronics Repair",
    stallNumber: "Stall No. D-15",
    marketSection: "Dry Goods Section",
    createdAt: DateTime(2026, 7, 9, 13, 10),
    overDueDate: DateTime(2026, 7, 23, 13, 10),
    isOverDue: false,
  ),
  TicketSummary(
    controlNumber: "11880",
    ticketStatus: TicketStatus.disputed,
    businessName: "Lydia's Carinderia",
    stallNumber: "Stall No. F-10",
    marketSection: "Food Court",
    createdAt: DateTime(2026, 6, 27, 11, 50),
    overDueDate: DateTime(2026, 7, 11, 11, 50),
    isOverDue: true, // Overdue
  ),
];